# Generated by Django 5.2.8 on 2025-12-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emojientry',
            name='unique_date_entry',
        ),
    ]
