# Generated by Django 5.2.8 on 2025-12-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emojientry_delete_emojiusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emojientry',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='emojientry',
            constraint=models.UniqueConstraint(fields=('data',), name='unique_date_entry'),
        ),
    ]
